"""
Fetches historical resolved markets from Polymarket Gamma API.
Falls back to Monte Carlo simulation if the API is unreachable.

For each resolved market we capture:
- The last trading prices (YES / NO) before resolution  →  simulated entry price
- The actual outcome (YES won or NO won)               →  ground truth

Monte Carlo assumptions (sourced from Polymarket public research):
  - Market prices: roughly uniform 0.05 – 0.95, skewed toward 0.1–0.5
  - YES win rate ≈ implied probability (efficient market baseline)
  - ~15% of markets have measurable mispricing (>5% off true probability)
  - Liquidity: log-normal, median ~$8k, mean ~$25k
  - Arbitrage: ~3% of active markets have YES+NO < 0.995
"""
from __future__ import annotations

import json
import math
import os
import random
import time
from dataclasses import dataclass, field
from typing import Optional

try:
    import requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False

GAMMA_BASE = "https://gamma-api.polymarket.com"
CACHE_FILE = "data/backtest_markets.json"


@dataclass
class HistoricalMarket:
    id: str
    question: str
    yes_price: float        # Last YES token price before resolution
    no_price: float         # Last NO token price before resolution
    yes_won: Optional[bool] # True=YES won, False=NO won, None=unknown
    volume: float
    liquidity: float
    synthetic: bool = False  # True if generated by Monte Carlo
    tags: list[str] = field(default_factory=list)

    @property
    def spread(self) -> float:
        """YES + NO - 1.0  (negative = arbitrage opportunity existed)."""
        return (self.yes_price + self.no_price) - 1.0

    @property
    def has_arbitrage(self) -> bool:
        return self.spread < -0.005

    @property
    def best_bet_side(self) -> Optional[str]:
        if self.yes_won is None:
            return None
        return "YES" if self.yes_won else "NO"

    @property
    def best_bet_price(self) -> float:
        return self.yes_price if self.best_bet_side == "YES" else self.no_price

    def passes_bot_filters(
        self,
        min_liquidity: float = 5000,
        min_price: float = 0.02,
        max_price: float = 0.98,
    ) -> bool:
        if self.liquidity < min_liquidity:
            return False
        if self.yes_price < min_price or self.yes_price > max_price:
            return False
        return True


# ------------------------------------------------------------------ #
#  API fetching (live)                                                 #
# ------------------------------------------------------------------ #

def _try_fetch_from_api(limit: int) -> list[dict]:
    """Attempt to fetch from Gamma API. Returns empty list on failure."""
    if not HAS_REQUESTS:
        return []

    raw_list: list[dict] = []
    offset = 0
    batch_size = 100

    while offset < limit:
        params = {
            "closed": "true",
            "limit": batch_size,
            "offset": offset,
            "order": "volume",
            "ascending": "false",
        }
        try:
            resp = requests.get(
                f"{GAMMA_BASE}/markets",
                params=params,
                timeout=15,
            )
            resp.raise_for_status()
            data = resp.json()
        except Exception as e:
            print(f"  API unavailable: {e}")
            return []

        if not data:
            break

        raw_list.extend(data)
        print(f"  Fetched {len(data)} markets (total: {len(raw_list)})")

        if len(data) < batch_size:
            break
        offset += batch_size
        time.sleep(0.4)

    return raw_list


def _parse_market(raw: dict) -> Optional[HistoricalMarket]:
    try:
        tokens = raw.get("tokens", [])
        if len(tokens) < 2:
            return None

        yes_token = next(
            (t for t in tokens if str(t.get("outcome", "")).upper() == "YES"),
            tokens[0],
        )
        no_token = next(
            (t for t in tokens if str(t.get("outcome", "")).upper() == "NO"),
            tokens[1],
        )

        yes_price = float(yes_token.get("price", 0) or 0)
        no_price = float(no_token.get("price", 0) or 0)

        if yes_price in (0.0, 1.0) and no_price in (0.0, 1.0):
            return None
        if yes_price <= 0 or no_price <= 0:
            return None

        yes_won = None
        outcome_prices = raw.get("outcomePrices")
        if outcome_prices:
            if isinstance(outcome_prices, str):
                try:
                    outcome_prices = json.loads(outcome_prices)
                except Exception:
                    pass
            if isinstance(outcome_prices, list) and len(outcome_prices) >= 2:
                try:
                    yes_won = float(outcome_prices[0]) > 0.5
                except (ValueError, TypeError):
                    pass

        if yes_won is None:
            winner = raw.get("winner")
            if winner:
                yes_won = str(winner).upper() == "YES"

        return HistoricalMarket(
            id=raw.get("id", ""),
            question=raw.get("question", ""),
            yes_price=yes_price,
            no_price=no_price,
            yes_won=yes_won,
            volume=float(raw.get("volume", 0) or 0),
            liquidity=float(raw.get("liquidity", 0) or 0),
            tags=[t.get("label", "") for t in raw.get("tags", []) if isinstance(t, dict)],
            synthetic=False,
        )
    except Exception:
        return None


# ------------------------------------------------------------------ #
#  Monte Carlo synthetic data generator                               #
# ------------------------------------------------------------------ #

def _log_normal_liquidity(rng: random.Random) -> float:
    """
    Polymarket liquidity is log-normally distributed.
    Median ~$8k, most markets $1k-$100k, some up to $500k+
    """
    mu = math.log(8_000)
    sigma = 1.4
    return math.exp(rng.gauss(mu, sigma))


def generate_synthetic_markets(n: int = 1000, seed: int = 42) -> list[HistoricalMarket]:
    """
    Generate realistic synthetic Polymarket markets using Monte Carlo.

    Assumptions (based on public Polymarket research):
      - Market price distribution: mostly in 0.1–0.9, higher density near extremes
      - Market efficiency: YES wins with probability ≈ YES_PRICE (calibrated market)
      - Mispricing: ~15% of markets are >5% off true probability
      - Arbitrage rate: ~3% of markets have YES+NO < 0.995 at some point
      - Bid-ask spread: normal markets have YES+NO = 1.00–1.06 (exchange takes margin)
      - Liquidity: log-normal, median $8k

    Returns n synthetic markets with realistic distributions.
    """
    rng = random.Random(seed)
    markets: list[HistoricalMarket] = []

    for i in range(n):
        # --- Generate YES price ---
        yes_price = rng.betavariate(1.5, 1.5) * 0.86 + 0.07  # range 0.07–0.93

        # --- Generate NO price based on market type ---
        r = rng.random()
        if r < 0.03:
            # TRUE arbitrage: YES + NO < 1.00 (~3% of markets)
            spread_deficit = rng.uniform(0.005, 0.025)
            no_price = (1.0 - yes_price) - spread_deficit
        else:
            # Normal market: YES + NO ≥ 1.00 (bid-ask spread means sum > 1)
            # Typical Polymarket spread = 1–6% over 1.00
            overpricing = rng.uniform(0.005, 0.06)
            no_price = (1.0 - yes_price) + overpricing

        # Clamp to valid range
        yes_price = max(0.03, min(0.97, yes_price))
        no_price = max(0.03, min(0.97, no_price))

        # --- Determine outcome ---
        # Base: market is ~70% calibrated (YES wins with prob = yes_price)
        # Mispricing: 15% chance the market is meaningfully off
        mispriced = rng.random() < 0.15
        if mispriced:
            # True probability deviates from market price by 10-25%
            true_yes_prob = yes_price + rng.choice([-1, 1]) * rng.uniform(0.10, 0.25)
            true_yes_prob = max(0.05, min(0.95, true_yes_prob))
        else:
            true_yes_prob = yes_price + rng.gauss(0, 0.04)  # small noise
            true_yes_prob = max(0.05, min(0.95, true_yes_prob))

        yes_won = rng.random() < true_yes_prob

        # --- Liquidity ---
        liquidity = _log_normal_liquidity(rng)

        markets.append(HistoricalMarket(
            id=f"synthetic_{i:05d}",
            question=f"Synthetic market #{i}",
            yes_price=round(yes_price, 4),
            no_price=round(no_price, 4),
            yes_won=yes_won,
            volume=liquidity * rng.uniform(2, 8),
            liquidity=round(liquidity, 2),
            synthetic=True,
        ))

    return markets


# ------------------------------------------------------------------ #
#  Main entry point                                                    #
# ------------------------------------------------------------------ #

def fetch_resolved_markets(limit: int = 1000, use_cache: bool = True) -> list[HistoricalMarket]:
    """
    Fetch resolved markets. Priority:
      1. Local cache (if exists and use_cache=True)
      2. Polymarket Gamma API (live fetch)
      3. Monte Carlo synthetic data (fallback)
    """
    # Try cache first
    if use_cache and os.path.exists(CACHE_FILE):
        try:
            with open(CACHE_FILE) as f:
                cached = json.load(f)

            # Check if cache contains real or synthetic data
            if cached and isinstance(cached[0], dict) and cached[0].get("synthetic"):
                print(f"  Loading synthetic data from cache ({len(cached)} markets)")
                markets = [HistoricalMarket(**r) for r in cached]
                return markets
            else:
                markets = [_parse_market(r) for r in cached]
                markets = [m for m in markets if m is not None]
                if markets:
                    print(f"  Loaded {len(markets)} real markets from cache")
                    return markets
        except Exception as e:
            print(f"  Cache error: {e} — will refetch")

    # Try live API
    print("  Attempting to fetch from Polymarket Gamma API...")
    raw_list = _try_fetch_from_api(limit)

    if raw_list:
        os.makedirs(os.path.dirname(CACHE_FILE), exist_ok=True)
        with open(CACHE_FILE, "w") as f:
            json.dump(raw_list, f)

        markets = [_parse_market(r) for r in raw_list]
        markets = [m for m in markets if m is not None]
        if markets:
            print(f"  Fetched and parsed {len(markets)} real markets from API")
            return markets

    # Fallback: synthetic Monte Carlo data
    print(f"\n  ⚠  API unavailable — using Monte Carlo synthetic data")
    print(f"  Generating {limit} synthetic markets with realistic distributions...")
    print(f"  Assumptions:")
    print(f"    - Price distribution: beta(1.5, 1.5) → realistic spread")
    print(f"    - Market efficiency: ~70% calibrated, ~15% mispriced")
    print(f"    - Arbitrage rate: ~3% of markets")
    print(f"    - Liquidity: log-normal, median $8k")
    print()

    markets = generate_synthetic_markets(n=limit)

    # Cache synthetic data
    os.makedirs(os.path.dirname(CACHE_FILE), exist_ok=True)
    with open(CACHE_FILE, "w") as f:
        json.dump([m.__dict__ for m in markets], f)

    return markets
